name: LCR_root
title: "Listen, Chat, and Remix: Text-Guided Soundscape Remixing for Enhanced Auditory Experience"
url: "https://listenchatremix.github.io"
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme
